### ISSUE TITLE
Force Calculation 

### ISSUE THREAD

**Issue by meetps** [samiranrl/Carrom_rl#10]
In `start_server.py` [L255](https://github.com/samiranrl/Carrom_rl/blob/master/1_player_server/start_server.py#L255)

```
force = MIN_FORCE + \
        float(max(min(force + gauss(0, noise2), 1), 0)) * MAX_FORCE
```

shouldn't this be :

```
force = MIN_FORCE + \
        float(max(min(force + gauss(0, noise2), 1), 0)) * (MAX_FORCE - MIN_FORCE)
```

**Comment by samiranrl** [comment]
No, we have set a minimum amount of force with which you must strike. This is mentioned in the readme (action section). Setting the force to 0 means giving up your turn.
