### ISSUE TITLE
Evaluation Mechanism

### ISSUE THREAD

**Issue by anchit** [samiranrl/Carrom_rl#13]
Can you please elaborate on the evaluation plan for the project. Specifically the weight-age give to the single player agent vs the two player agent  . Also will only the final performance of out agent be considered or also the algorithm we implemented , because given the complex nature of the problem it is highly likely that a RL method we chose to implement doesn't give impressive performance due to lack of Hardware / training time we could give to the model  and given the deadline we are not able to try out alternative models that might have worked better.

**Comment by samiranrl** [comment]
Hey, I have forwarded this query to sir..
