### ISSUE TITLE
What happened to the initial positions?

### ISSUE THREAD

**Issue by AgarwalPragy** [samiranrl/Carrom_rl#14]
Some changes were made last night which change the initial coin locations. The new locations don't seem symmetric.
![image](https://cloud.githubusercontent.com/assets/7423639/20055167/e31b1540-a505-11e6-9195-256c21d3342f.png)

**Also, the striker's Y-pos is still inconsistent across the 1-player and 2-player settings.**

Since the striker's location, initial coin positions and start-game state distributions are important to the agent, we can't have them change frequently.

We only have a few days remaining till the submission, and everyone needs to train their agents.

It will be nice to have a symmetric, bug free, consistent environment soon, since it will be difficult to re-train the agent.

**Comment by samiranrl** [comment]
I fixed the P1 server y coordinate to match the P2 Server.. As for the initial coin positions, they are fixed and will no longer change.
