### ISSUE TITLE
Angle Calculation for 2 player

### ISSUE THREAD

**Issue by sakshimaskara07** [samiranrl/Carrom_rl#17]
For 2  players , when the striker is at player1 (white) side, at angle = 0 it is going in the right direction which is correct. But when the striker is at player2 (black) side, at angle = 0 it should go in the left direction from the normal view (i.e. right direction from its own view). But for both the cases it is going in the same(right) direction for angle=0 when seen from our side(normal). 
![screenshot from 2016-11-11 02-14-17](https://cloud.githubusercontent.com/assets/20149626/20193670/0d563f54-a7b5-11e6-9c81-8ac973809d60.png)
![screenshot from 2016-11-11 02-15-58](https://cloud.githubusercontent.com/assets/20149626/20193671/0d5f78ee-a7b5-11e6-929e-b9d553e89bdf.png)

**Comment by samiranrl** [comment]
fixed, please check once.

**Comment by AgarwalPragy** [comment]
Thanks for the fix. Although, it would be good if we could avoid changes just 4 days before submission.
We already have tons of training data, and I will need to check if this change makes it unusable.

It will be nice to have a final version, on which the agents will be tested on.
^_^
