### ISSUE TITLE
Different pockets in 1 player and two player Utils

### ISSUE THREAD

**Issue by sb0210** [samiranrl/Carrom_rl#20]
@samiranrl Different pocket positions are getting used in 1-player server and in 2 player server. Is this by intention or a bug. If it is a bug, please either correct it and inform the students on the moodle.
https://github.com/samiranrl/Carrom_rl/blob/master/2_player_server/Utils.py#L120
```
    for i in [(44.1, 43.1), (756.5, 43), (756.5, 756.5), (44, 756.5)]:
```
https://github.com/samiranrl/Carrom_rl/blob/master/1_player_server/Utils.py#L120
```
    for i in [(44.1, 44.1), (755.9, 44.1), (755.9, 755.9), (44.1, 755.9)]:
```

**Comment by samiranrl** [comment]
I did not correct this as its too late and people will have to retrain their agents. Since the 1player and 2player agent logic is separated, it will not affect anything.
