### ISSUE TITLE
Scoring issue

### ISSUE THREAD

**Issue by ujjwal9895** [samiranrl/Carrom_rl#8]
1. When only queen and a coin remains, pocketing the coin gives reward of 1 and increases score by 1 which makes the overall score in the end much greater than 21.
2. Even when the board becomes empty, the server sends an empty state list instead of closing the connection.
3. If more than one coin is pocketed in the same turn with the queen, a reward of only 4 is received which instead should be more.

**Comment by samiranrl** [comment]
Hey.. I have checked 1,2 and 3. It is working fine. Are you using the latest version of the server? If yes,  Can you give me a videocast of this?

**Comment by ujjwal9895** [comment]
I am working using the latest version of server.

In the link below, I have added two videos.
https://drive.google.com/open?id=0B-fV1eAK3KyxcnNpVmdyRm1RQkE
1. In experiment of video "highscore", in the end, a coin and a queen remains and pocketing coin increases score by one every time.
2. In the video "highscore", at the end of video, error "Error in sending:" is shown which is because after sending empty state list to agent, the server closes connection, which should be before that.
3. In the video "lowscore", when the queen is pocketed and after that if black coin is pocketed, reward of only +2 is given which should be +4 and due to some issue, the score after the end of experiment if only 18.

**Comment by samiranrl** [comment]
I fixed 1 and 3. For 2, the server is closing the connection when the board is cleared. This does not affect the final outcome. Can you check if 1 and 3 are working fine now? and if 2 is affecting the result?

Thanks...

**Comment by ujjwal9895** [comment]
Yeah they are fixed now and in 2, it was just giving an error but does not affect the result.

**Comment by samiranrl** [comment]
Okay, thanks again for your help.
