### ISSUE TITLE
Lates Bug Fix

### ISSUE THREAD

**Issue by anchit** [samiranrl/Carrom_rl#9]
The latest bug fix to address the scoring issue (regarding the queen) has now made the problem even tougher. We are getting higher average turns to clear because of it. As this was so close to the deadline I am sure many students might even fail to pull the latest code and notice the difference.

**Comment by sb0210** [comment]
Yeah, @samiranrl  it would be great if you post this on moodle. Many students don't know about this.

**Comment by samiranrl** [comment]
@Anzhit , if you look at the fix carefully, it affects how the score is updated. It does not affect the rules
of the game or the number of turns to clear the board. We have tested this independently. Still, if students are having genuine problems, it will be taken into consideration.

**Comment by anchit** [comment]
@samiranrl It did seem to affect my agent probably because i was using the score to set some parameters. I did change my agent to reflect you bug fix and it works to a similar level now
